-- MySQL Script generated by MySQL Workbench
-- Sun May 17 20:08:07 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema data-jpa-index-compare
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `data-jpa-index-compare` ;

-- -----------------------------------------------------
-- Schema data-jpa-index-compare
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `data-jpa-index-compare` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
SHOW WARNINGS;
USE `data-jpa-index-compare` ;

-- -----------------------------------------------------
-- Table `case1_root`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `case1_root` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `created_at` TIMESTAMP(3) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `case1_child`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `case1_child` (
  `root` BIGINT UNSIGNED NOT NULL,
  `seq` INT UNSIGNED NOT NULL,
  `created_at` TIMESTAMP(3) NOT NULL,
  PRIMARY KEY (`root`, `seq`),
  CONSTRAINT `fk_case1_child_pk_case1_root`
    FOREIGN KEY (`root`)
    REFERENCES `case1_root` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
